### ISSUE TITLE
Ultrasonic

### ISSUE THREAD

**Issue by DiamondValve** [jdp8y/LambdAC#1]
I have still yet to find out how to define each ultrasonic sensor individually.

**Comment by DiamondValve** [comment]
May separate the sensors into different functions if i can.

**Comment by jdp8y** [comment]
I may have fixed it, I defined the different pings.

**Comment by DiamondValve** [comment]
kk.

**Comment by DiamondValve** [comment]
josh
NewPing is a command.

**Comment by jdp8y** [comment]
jesus :laughing:
